/*
 Generated by typeshare 1.3.0
*/

export interface UserLogin {
	username: string;
	password: string;
}

export interface NewUser {
	name: string;
	surname: string;
	username: string;
	email: string;
	password: string;
	passwordConfirm: string;
}

