/*
 Generated by typeshare 1.3.0
*/

export interface UserLogin {
	username: string;
	password: string;
}

export interface Contractor {
	_id: string;
	name: string;
}

export interface MessageResponse {
	status: string;
}

